### ISSUE TITLE
allow more than one instructor

### ISSUE THREAD

**Issue by lesliepearson** [ajbraus/courseboard#16]

**Comment by Saturn-V** [comment]
1. update the form
2. update the model to have a coInstructor attribute
3. update where you see the instructors in course.instructor add course.coInstructor name etc.

**Comment by Saturn-V** [comment]
```
- git checkout master
- git pull
- git checkout -b <branch-name> (the -b flag is to create and checkout a new flag. you can leave it off if the branch already exists on your local machine)
- git pull origin <branch-name> (you want to pull the remote branch if this is not a new branch in case someone else has pushed changes to the branch)
- git merge master
- fix merge conflicts
- git push origin <branch-name>
- create pr on github
```

**Comment by lesliepearson** [comment]
@Saturn-V update which model to have a `coInstructor` attribute? the class? does this mean you only allow one `coInstructor`? maybe an array of instructors would be a way to add as many instructors to a class rather than limiting it to one `coInstructor`. what do you think?

also, if you think it'd be helpful to add instructions on how to contribute using git, you could create a PR to add that to the README or you could create another MD file on how to contribute :)

**Comment by Saturn-V** [comment]
@lesliekimm Update the `course` model. The way it's currently setup is such that there's a `instructor` and `coInstructor` property to every course. I like the idea of having an array of instructors, but as of now, every course only has at most, 2 instructors, so I don't see a need for introducing an array. 

I can talk it over with some of the instructors, and see if they plan to introduce courses with more than 2 instructors. If they do, then I think implementing the array of instructors would be a great idea. What are your thoughts?

In regards to the README, I can make a PR sometime this week for that. Hopefully we can get some more contribution going on this!

**Comment by lesliepearson** [comment]
i actually don't remember how we originally set it up. but if we're querying for an instructor AND a co-instructor, we could just query once for an array of instructors. i'd have to take a look at it again. also it was more of a general suggestion if this were to ever be used outside of make school. it'd be awesome to see this become a product that other schools/teaching institutions could use as well!

i see that you made a PR! awesome! i'll try to take a look later this week!!!
